import { writeFileSync } from "node:fs";
import { FORMS, PATCHES, INCOME, LEATHER } from "../src/game/data.ts";
const forms = PATCHES.map(
  (p, i) =>
    `{${p.cost},${p.time},${p.income},{${FORMS[i].map((c) => `{${c.map(([x, y]) => `{${x},${y}}`).join(",")}}`).join(",")}}}`,
).join(",\n");
writeFileSync(
  new URL("../cpp/data.hpp", import.meta.url),
  `// Generated by scripts/generate-data.ts; edit src/game/patches.json instead.\n#pragma once\n#include <vector>\n#include <utility>\nnamespace pw {\nstruct Piece {int cost,time,income; std::vector<std::vector<std::pair<int,int>>> forms;};\ninline const std::vector<Piece> pieces={${forms}};\ninline constexpr int incomes[]={${INCOME.join(",")}};\ninline constexpr int leathers[]={${LEATHER.join(",")}};\n}\n`,
);
